### ISSUE TITLE
Possible bug or a misleading typo

### ISSUE THREAD

**Issue by jmacias1503** [raiyanyahya/dallecli#13]
Hi, just started using this cli tool, and i have encountered this issue, don't know if it's because of the prompt in the size, but any time I try to put a specific size, outputs me an error. This have happened with any prompt I gave to it. Maybe I need to put more parameters, I would like to have some help with this
## Prompt
```bash
dallecli generate --prompt 'my prompt' --size '1920x1080' # A size example
```

## Output
```
Failed to generate image. Please try again with a different prompt.
```

**Comment by raiyanyahya** [comment]
The openai api for dalle only supports images sizes of 256x256, 512x512, or 1024x1024 pixels. This is as per documentation.

So the size that you mentioned is not supported. Thanks for bringing this up though, I will add those as a click options argument and update it in the readme in the next version which I will release tomorrow.

**Comment by jmacias1503** [comment]
> The openai api for dalle only supports images sizes of 256x256, 512x512, or 1024x1024 pixels. This is as per documentation.
> 
> So the size that you mentioned is not supported. Thanks for bringing this up though, I will add those as a click options argument and update it in the readme in the next version which I will release tomorrow.

Thank you!! Didn't know of this
