### ISSUE TITLE
Inpainting 

### ISSUE THREAD

**Issue by maxp-hover** [raiyanyahya/dallecli#24]
Dall-e has the ability to edit an existing image using a prompt, see here https://www.educative.io/answers/how-to-edit-an-image-using-dalle-api

I tried to clone the project but I couldn't figure out how to actually run the CLI locally in development. Perhaps you could also include development instructions in the README?

**Comment by raiyanyahya** [comment]
The cli can be run locally by just cloning the repo and installing the cli with a symlink "pip install -e . " 
Any changes to the code will then be automatically reflected to the local copy of the cli.

**Comment by Konfekt** [comment]
I recommend `pip install --user --upgrade pipx && pipx install git+https://github.com/raiyanyahya/dallecli`
