### ISSUE TITLE
Image viewer opens without any file

### ISSUE THREAD

**Issue by carnager** [raiyanyahya/dallecli#57]
I don't know how dallecli opens the image viewer. It seems to use my default application for images (qimgv). 
But qimgv always opens without any actual image. 

I am actually not sure what is causing this, but i suspect it's not properly telling the path to the image?

Also: maybe it would be a nice addition if one could specify an image viewer to use.

**Comment by raiyanyahya** [comment]
Hi! This is a bit tricky. I dont want to open system applications via the cli's python process. The cli current just uses the system default to open the images. You could try setting a different app as a default for opening the image. Let me know how that goes for you!
