### ISSUE TITLE
read variable OPENAI_API_KEY

### ISSUE THREAD

**Issue by carnager** [raiyanyahya/dallecli#58]
**Is your feature request related to a problem? Please describe.**
I am trying to automate setup of dallecli for termux and the only thing needing manual input is the setup of an API key, because the update command only allows interactive usage.

I see 2 solutions for this: 

1. allow to provide the api key directly from commandline `dallecli update myapikey`
2. read OPENAI_API_KEY variable to update configuration automaticaly if not present.

**Comment by raiyanyahya** [comment]
Thats a great suggestion. This has been implemented in and released. Please update :)
